### ISSUE TITLE
What about removing demo folders?

### ISSUE THREAD

**Issue by MrPaulDriver** [balbuf/drupal-libraries-installer#3]
It is sometimes recommended that demo folders and other items are removed from a library. Wondering what is the best approach to deal with this.

- Commit them to git, but ignore these folders
- Remove folders after download and then remove extra/drupal-libraries code from composer.json
- Something else?

Relative newbie to both composer and git, so looking for ideas about best practice.

**Comment by balbuf** [comment]
Hi @MrPaulDriver, sorry I missed this issue!

I'm actually not super familiar with that recommendation, but I imagine it comes from a time when you might be committing 3rd-party library code to your repo. In that case, you'd want to strip out anything you don't need to avoid added unnecessary weight to the repo.

However, when using composer, you don't want to commit _any_ 3rd-party code to your repo, and in fact that is one of the primary benefits of the tool. Instead, you commit the `composer.json` and `composer.lock` files, and each person working on the repo would run `composer install` to download the requisite dependencies (including Drupal libraries). In this case, there is no concern about stripping unneeded files such as demo folders as they aren't stored in the repo anyway.

I'm going to close this issue, but feel free to follow-up / reopen as necessary!
